#!/bin/bash
ln -sf libcairo.so.2 /opt/EdrawMax-11/lib/libcairo.so
ln -sf libcrypto.so.1.0.0 /opt/EdrawMax-11/lib/libcrypto.so
ln -sf libcurl.so.4 /opt/EdrawMax-11/lib/libcurl.so
ln -sf libEGL.so.1.0.0 /opt/EdrawMax-11/lib/libEGL.so
ln -sf libEGL.so.1.0.0 /opt/EdrawMax-11/lib/libEGL.so.1
ln -sf libQt5Core.so.5.6.1 /opt/EdrawMax-11/lib/libQt5Core.so
ln -sf libQt5Core.so.5.6.1 /opt/EdrawMax-11/lib/libQt5Core.so.5
ln -sf libQt5Core.so.5.6.1 /opt/EdrawMax-11/lib/libQt5Core.so.5.6
ln -sf libQt5DBus.so.5.6.1 /opt/EdrawMax-11/lib/libQt5DBus.so
ln -sf libQt5DBus.so.5.6.1 /opt/EdrawMax-11/lib/libQt5DBus.so.5
ln -sf libQt5DBus.so.5.6.1 /opt/EdrawMax-11/lib/libQt5DBus.so.5.6
ln -sf libQt5EglDeviceIntegration.so.5.6.1 /opt/EdrawMax-11/lib/libQt5EglDeviceIntegration.so
ln -sf libQt5EglDeviceIntegration.so.5.6.1 /opt/EdrawMax-11/lib/libQt5EglDeviceIntegration.so.5
ln -sf libQt5EglDeviceIntegration.so.5.6.1 /opt/EdrawMax-11/lib/libQt5EglDeviceIntegration.so.5.6
cp /home/tiny/.local/share/tiny/edraw/libQt5Gui.so.5.6.1 /opt/EdrawMax-11/lib/libQt5Gui.so.5.6.1
ln -sf libQt5Gui.so.5.6.1 /opt/EdrawMax-11/lib/libQt5Gui.so
ln -sf libQt5Gui.so.5.6.1 /opt/EdrawMax-11/lib/libQt5Gui.so.5
ln -sf libQt5Gui.so.5.6.1 /opt/EdrawMax-11/lib/libQt5Gui.so.5.6
ln -sf libQt5Network.so.5.6.1 /opt/EdrawMax-11/lib/libQt5Network.so
ln -sf libQt5Network.so.5.6.1 /opt/EdrawMax-11/lib/libQt5Network.so.5
ln -sf libQt5Network.so.5.6.1 /opt/EdrawMax-11/lib/libQt5Network.so.5.6
ln -sf libQt5OpenGL.so.5.6.1 /opt/EdrawMax-11/lib/libQt5OpenGL.so
ln -sf libQt5OpenGL.so.5.6.1 /opt/EdrawMax-11/lib/libQt5OpenGL.so.5
ln -sf libQt5OpenGL.so.5.6.1 /opt/EdrawMax-11/lib/libQt5OpenGL.so.5.6
ln -sf libQt5PrintSupport.so.5.6.1 /opt/EdrawMax-11/lib/libQt5PrintSupport.so
ln -sf libQt5PrintSupport.so.5.6.1 /opt/EdrawMax-11/lib/libQt5PrintSupport.so.5
ln -sf libQt5PrintSupport.so.5.6.1 /opt/EdrawMax-11/lib/libQt5PrintSupport.so.5.6
ln -sf libQt5Sql.so.5.6.1 /opt/EdrawMax-11/lib/libQt5Sql.so
ln -sf libQt5Sql.so.5.6.1 /opt/EdrawMax-11/lib/libQt5Sql.so.5
ln -sf libQt5Sql.so.5.6.1 /opt/EdrawMax-11/lib/libQt5Sql.so.5.6
ln -sf libQt5Svg.so.5.6.1 /opt/EdrawMax-11/lib/libQt5Svg.so
ln -sf libQt5Svg.so.5.6.1 /opt/EdrawMax-11/lib/libQt5Svg.so.5
ln -sf libQt5Svg.so.5.6.1 /opt/EdrawMax-11/lib/libQt5Svg.so.5.6
cp /home/tiny/.local/share/tiny/edraw/libQt5Widgets.so.5.6.1 /opt/EdrawMax-11/lib/libQt5Widgets.so.5.6.1
ln -sf libQt5Widgets.so.5.6.1 /opt/EdrawMax-11/lib/libQt5Widgets.so
ln -sf libQt5Widgets.so.5.6.1 /opt/EdrawMax-11/lib/libQt5Widgets.so.5
ln -sf libQt5Widgets.so.5.6.1 /opt/EdrawMax-11/lib/libQt5Widgets.so.5.6
cp /home/tiny/.local/share/tiny/edraw/libQt5XcbQpa.so.5.6.1 /opt/EdrawMax-11/lib/libQt5XcbQpa.so.5.6.1
ln -sf libQt5XcbQpa.so.5.6.1 /opt/EdrawMax-11/lib/libQt5XcbQpa.so
ln -sf libQt5XcbQpa.so.5.6.1 /opt/EdrawMax-11/lib/libQt5XcbQpa.so.5
ln -sf libQt5XcbQpa.so.5.6.1 /opt/EdrawMax-11/lib/libQt5XcbQpa.so.5.6
ln -sf libQt5Xml.so.5.6.1 /opt/EdrawMax-11/lib/libQt5Xml.so
ln -sf libQt5Xml.so.5.6.1 /opt/EdrawMax-11/lib/libQt5Xml.so.5
ln -sf libQt5Xml.so.5.6.1 /opt/EdrawMax-11/lib/libQt5Xml.so.5.6
ln -sf libtiff.so.5 /opt/EdrawMax-11/lib/libtiff.so

ln -sf /usr/lib/aarch64-linux-gnu/libidn.so.12 /opt/EdrawMax-11/lib/libidn.so.11
ln -sf /usr/lib/aarch64-linux-gnu/libstdc++.so.6 /opt/EdrawMax-11/lib/libstdc++.so.6
sudo apt install -y /home/tiny/.local/share/tiny/edraw/libldap-2.4-2_2.4.57+dfsg-3+deb11u1_arm64.deb
